apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: whoami-ingress
  namespace: dev
spec:
  rules:
  - host: 'whoami.heemels.net'
    http:
      paths:
      - backend:
          serviceName: whoami
          servicePort: 80