apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/ssl-temporary-redirect: "true"
  name: whoami-ingress
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: whoami
          servicePort: http
        path: /whoami
