apiVersion: v1
data:
  nginx.conf: |
    worker_processes 1;
    error_log stderr warn;
    pid /run/nginx.pid;

    events {
        worker_connections 512;
        multi_accept on;
        use epoll;
    }

    http {
        charset utf-8;
        server_tokens off;
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 30;
        client_max_body_size 50M;

        include mime.types;
        default_type application/octet-stream;

        log_format main_json_combined escape=json
            '{'
                '"request_id":"$request_id",'
                '"time_local":"$time_local",'
                '"remote_addr":"$remote_addr",'
                '"remote_user":"$remote_user",'
                '"message":"$request",'
                '"status":"$status",'
                '"body_bytes_sent":"$body_bytes_sent",'
                '"request_time":"$request_time",'
                '"request_length":"$request_length",'
                '"http_host":"$http_host",'
                '"http_referrer":"$http_referer",'
                '"http_user_agent":"$http_user_agent",'
                '"http_x_forwarded_for":"$http_x_forwarded_for",'
                '"severity":"INFO",'
                '"logName":"nginx"'
            '}';

        access_log /dev/stdout main_json_combined;
        error_log /dev/stderr warn;

        server {
            listen [::]:80 default_server;
            listen 80 default_server;
            server_name _;

            location / {
                proxy_pass http://localhost:9898/;
            }
        }
    }
kind: ConfigMap
metadata:
  name: confnginx
