apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: default
spec:
  ports:
    - port: 9898
      targetPort: 9898
      name: http
    - port: 80
      targetPort: 80
      name: httpnginx
  selector:
    app: podinfo
