kind: Deployment
apiVersion: apps/v1
metadata:
  name: podinfo
  namespace: default
  labels:
    app: podinfo
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: podinfo
        image: quay.io/stefanprodan/podinfo:3.2.0
        command:
        - ./podinfo
        - --port=9898
        ports:
        - containerPort: 9898
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9898
          initialDelaySeconds: 1
          periodSeconds: 5
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9898
          initialDelaySeconds: 1
          periodSeconds: 10
          failureThreshold: 2
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "10m"
      - name: nginx
        image: nginx:1.17-alpine
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "10m"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: confnginx
