apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
  name: podinfo-ingress
  namespace: dev
spec:
  rules:
  - http:
      paths:
      - path: /podinfo
        backend:
          serviceName: podinfo
          servicePort: 9898